# Generated by Django 5.2.9 on 2025-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField(verbose_name='Первое число')),
                ('num2', models.FloatField(blank=True, null=True, verbose_name='Второе число')),
                ('operation', models.CharField(choices=[('add', 'Сложение'), ('subtract', 'Вычитание'), ('multiply', 'Умножение'), ('divide', 'Деление'), ('power', 'Возведение в степень'), ('sqrt', 'Квадратный корень')], max_length=20, verbose_name='Операция')),
                ('result', models.FloatField(verbose_name='Результат')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'История вычислений',
                'verbose_name_plural': 'История вычислений',
                'ordering': ['-timestamp'],
            },
        ),
    ]
